// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTuST3a_baWKx6Ehm-k_cvVgHlHXD7QM',
    appId: '1:364310885685:android:e0bb8c57adef765ee8c87c',
    messagingSenderId: '364310885685',
    projectId: 'tryal-adf7d',
    databaseURL: 'https://tryal-adf7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tryal-adf7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3RuABAorhXrpOh9_Wbs9x6KCzfnhzOnY',
    appId: '1:364310885685:ios:95383912f90590e2e8c87c',
    messagingSenderId: '364310885685',
    projectId: 'tryal-adf7d',
    databaseURL: 'https://tryal-adf7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tryal-adf7d.appspot.com',
    androidClientId: '364310885685-fn6qvqj2nmtrlkgrrthrvd9tujrvfl6g.apps.googleusercontent.com',
    iosClientId: '364310885685-6f3jda8jgrdin0dr5h1qc92nqi04cro7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitechMobileApps',
  );
}
